///Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_MOVIE_VO = 3;
const int HIVE_TYPE_ID_ACTOR_VO = 4;
const int HIVE_TYPE_ID_CINEMA_VO = 5;
const int HIVE_TYPE_ID_COLLECTION_VO = 6;
const int HIVE_TYPE_ID_GENRE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;
const int HIVE_TYPE_ID_TIMESLOT_VO = 11;
const int HIVE_TYPE_ID_SNACK_VO = 12;
const int HIVE_TYPE_ID_CINEMALIST_FOR_HIVE_VO = 13;
const int HIVE_TYPE_ID_ACTORLIST_FOR_HIVE_VO = 14;


///Box Names
const String BOX_NAME_USER_VO = "BOX_NAME_USER_VO";
const String BOX_NAME_CARD_VO = "BOX_NAME_CARD_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const String BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const String BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";
const String BOX_NAME_TIMESLOT_VO = "BOX_NAME_TIMESLOT_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
